---
- name: 'Provision Image'
  hosts: default
  become: true
  gather_facts: no
  vars:
    nfs_server: NFS_SERVER.EXAMPLE.COM
    nfs_share: /nfs_share
    local_user: packer
    working_dir: /home/{{ local_user }}/work
  vars_files:
  - vars/yum_repos.yml
  tasks:
  - name: Add Yum Repos
    yum_repository:
      name: "{{ repo.name }}"
      state: present
      file: "{{ repo.file }}"
      description: "{{ repo.description }}"
      baseurl: "{{ repo.baseurl }}"
      enabled: "{{ repo.enabled }}"
      gpgcheck: "yes"
      gpgcakey: "{{ repo.gpgcakey }}"
    loop_control:
      loop_var: repo
    loop: "{{ yum_repos }}"
    register: repo_add
    tags:
    - docker
    - git

  - name: Add GPG Keys
    rpm_key:
      key: "{{ item }}"
      state: present
    with_items:
    - https://download.docker.com/linux/centos/gpg
    - https://packages.endpoint.com/endpoint-rpmsign-7.pub
    - https://packages.microsoft.com/keys/microsoft.asc
    tags:
    - docker
    - git

  - name: Yum Clean
    command: yum --disableplugin=rhnplugin clean all 
    args:
      warn: no
    when: repo_add is changed
    tags:
    - git

  - name: Install Git 
    yum:
      name: git
      state: latest
    tags:
    - git
  
  - name: Check Git Version
    command: git --version
    changed_when: no
    register: git_version
    tags:
    - git

  - name: Retry - Git Install
    yum:
      name: git
      state: latest
    when: '"git version 2.30" not in git_version.stdout'
    tags:
    - git
  
  - name: Register with RHSM
    redhat_subscription:
      username: "{{ rhsm_user }}"
      password: "{{ rhsm_pass }}"
      pool: "{{ rhsm_pool }}"
      state: present
      force_register: yes
    tags:
    - docker
    - rhsm

  - name: Enable RHEL 7 Extras
    rhsm_repository:
      name: "{{ repo }}" 
      state: enabled
    loop_control:
      loop_var: repo
    loop:
    - rhel-7-server-rpms
    - rhel-7-server-extras-rpms
    - rhel-7-server-optional-rpms
    tags:
    - docker
    - packages
    - rhsm

  - name: Install Packages
    yum:
      name: 
      - docker-ce
      - code
      - autoconf
      - automake
      - bc
      - binutils
      - curl
      - http://fr2.rpmfind.net/linux/centos/7.9.2009/os/x86_64/Packages/doxygen-1.8.5-4.el7.x86_64.rpm
      - https://download-ib01.fedoraproject.org/pub/epel/7/x86_64/Packages/m/meld-3.16.4-2.el7.noarch.rpm
      - gcc-c++
      - git
      - graphviz
      - libGLU
      - libstdc++
      - libtool
      - libwayland-egl
      - libwayland-server
      - libwayland-client
      - libxcb
      - libxcb-devel
      - m4
      - make
      - mesa-libGLU-devel
      - mesa-libGL
      - perl
      - python
      - sqlite
      - sqlite-devel
      - sudo
      - valgrind
      state: present
    tags:
    - docker
    - packages

  - name: Deregister from RHSM
    redhat_subscription:
      state: absent
    tags:
    - docker
    - packages
    - rhsm

  - name: Add 'docker' Group
    group:
      name: docker
      state: present
    tags:
    - docker

  - name: Enable Docker Service
    systemd:
      name: docker
      state: started
      enabled: yes
      daemon_reload: yes
    tags:
    - docker

  - name: Create 'work' Directory
    become: false
    file:
      path: "{{ working_dir }}"
      state: directory
      owner: "{{ local_user }}"
      group: "{{ local_user }}"
      mode: "0755"
    tags:
    - NetBeans

  - name: Install NetBeans
    become: false
    get_url:
      url: https://mirror.jframeworks.com/apache/netbeans/netbeans/12.3/Apache-NetBeans-12.3-bin-linux-x64.sh
      dest: "{{ working_dir }}/"
      mode: '0755'
    tags:
    - NetBeans

  - name: Get Linux Canbus Driver
    get_url:
      url: https://www.kvaser.com/downloads-kvaser/?utm_source=software&utm_ean=7330130980754&utm_status=latest
      dest: /root/
    register: driver_download
    tags:
    - canbus

  - name: Install Canbus
    block:
    - name: Unzip Linux Canbus Driver
      unarchive:
        src: /root/linuxcan.tar.gz
        dest: /usr/src/
        remote_src: yes

    - name: Make linuxcan
      make:
        chdir: /usr/src/linuxcan
        
    - name: Make install linuxcan
      make:
        chdir: /usr/src/linuxcan
        target: install

    - name: Execute mhydra.sh
      command: /usr/sbin/mhydra.sh start

    when: driver_download is changed
    tags:
    - canbus

  - name: Mount NFS_Share
    mount:
      src: "{{ nfs_server}}:{{nfs_share}}"
      path: /mnt/dev_tools
      fstype: nfs
      opts: defaults
      dump: '0'
      passno: '0'
      state: mounted
    tags:
    - nfs

  - name: Enable GUI
    file:
      src: /usr/lib/systemd/system/graphical.target
      dest: /etc/systemd/system/default.target
      state: link
    tags:
    - enable_gui